// This is a simple global “storage object”
// Think of it like a lightweight database for your page
const App = {
  graphCache: null,      // stores all figurative language nodes (metaphor/simile/aphorism)
  sentenceCache: null,   // stores all paragraph/sentence nodes + their tokenized words
  activeWord: null       // remembers what word the user clicked last (used for graph focus)
};


/* =========================
INIT (ENTRY POINT)
========================= */

// This runs once the HTML generated by XSLT has fully loaded into the browser

document.addEventListener("DOMContentLoaded", () => {

  // STEP 1: scan DOM and build “data model” for figurative language nodes
  cacheDocument();

  // STEP 2: scan DOM and build “data model” for sentences
  cacheSentences();

  // STEP 3: attach click handlers to UI buttons
  initViewButtons();

  // STEP 4: attach click handlers to metaphor/simile/aphorism nodes
  initMetaphorClicks();

});


/* =========================
CACHE FIGURATIVE LANGUAGE (NODE-BASED)
========================= */

// PURPOSE:
// Build a JavaScript array of all <metaphor>, <simile>, <aphorism> elements in the DOM
// so we can quickly search and compute relationships later (instead of querying DOM repeatedly)

function cacheDocument() {

  // Selects actual DOM elements created by XSLT (NOT class-based anymore)
  const items = document.querySelectorAll('metaphor, simile, aphorism');

  // Convert NodeList → Array and map into structured JS objects
  App.graphCache = Array.from(items).map(el => ({

    el,  // store the actual DOM node (important for clicking + navigation)

    // tagName is used instead of classList since we are using XML-like elements
    type: el.tagName.toLowerCase(),

    // sentence reference passed from XSLT (data-sentence attribute)
    sentenceId: el.dataset.sentence,

    // convert text inside this node into an array of words
    words: tokenize(el.textContent)

  }));

}


/* =========================
CACHE ALL SENTENCES
========================= */

// PURPOSE:
// Build a second dataset representing each sentence (<p> node)
// including its words and whether it contains figurative language

function cacheSentences() {

  // Select all sentence containers (created by XSLT)
  const sentences = document.querySelectorAll('p');

  App.sentenceCache = Array.from(sentences).map(p => {

    // convert full sentence text into array of meaningful words
    const words = tokenize(p.textContent);

    // check if sentence contains ANY figurative language nodes inside it
    // (this replaces class-based logic with structural DOM logic)
    const hasFigurative =
      p.querySelector('metaphor, simile, aphorism') !== null;

    return {

      el: p,              // store DOM node for scrolling/navigation
      words,             // tokenized version of sentence
      hasFigurative      // boolean flag used for styling in UI

    };

  });

}


/* =========================
TOKENIZER (TEXT → WORD ARRAY)
========================= */

// PURPOSE:
// Convert raw sentence text into clean word list for analysis

function tokenize(text) {

  // common words removed to improve semantic meaning of graph
  const stopwords = new Set([
    "the","and","is","in","of","a","to","but","with","for","on","into","he","who",
    "those","him","her","when","his","them","here","they","all","you","has","only",
    "that","it","can","was","if","my","there","as","i","or","this","have","had",
    "been","are","were","be","by","at","an","so","do","does","did","not"
  ]);

  return text
    .toLowerCase()              // normalize case
    .replace(/[^a-z\s]/g, '')   // remove punctuation
    .split(/\s+/)               // split into words
    .filter(w => w && !stopwords.has(w)); // remove empty + stopwords

}


/* =========================
VIEW SWITCHING SYSTEM
========================= */

// PURPOSE:
// Show ONE panel at a time (reading / analysis / metaphor view)

function showView(viewId) {

  // hide all views
  document.querySelectorAll('.view')
    .forEach(v => v.classList.remove('active'));

  // show selected view
  document.getElementById(viewId)
    .classList.add('active');

}


/* =========================
VIEW BUTTON EVENT BINDING
========================= */

// PURPOSE:
// Connect UI buttons to view switching system

function initViewButtons() {

  document.getElementById("view-reading")
    .addEventListener("click", () => showView("reading-view"));

  document.getElementById("view-analysis")
    .addEventListener("click", () => showView("analysis-view"));

  document.getElementById("view-metaphor")
    .addEventListener("click", () => showView("metaphor-view"));

}


/* =========================
METAPHOR CLICK HANDLERS
========================= */

// PURPOSE:
// When user clicks a figurative phrase,
// open analysis view for its sentence

function initMetaphorClicks() {

  document.querySelectorAll('metaphor, simile, aphorism')
    .forEach(el => {

      el.addEventListener("click", () => {

        openAnalysis(el);

      });

    });

}


/* =========================
ANALYSIS VIEW LOADER
========================= */

// PURPOSE:
// When a figurative phrase is clicked:
// 1. find its sentence
// 2. show sentence
// 3. build word-level interaction panel

function openAnalysis(el) {

  // get sentence ID from XSLT-generated attribute
  const sentenceId = el.dataset.sentence;

  // locate sentence DOM element
  const paragraph = document.getElementById(sentenceId);

  if (!paragraph) return; // safety check

  // switch UI to analysis panel
  showView("analysis-view");

  // show full sentence text in UI
  document.getElementById("analysis-sentence")
    .textContent = paragraph.textContent;

  // build clickable word buttons from sentence
  buildWordPanel(paragraph.textContent);

  // scroll sentence into view in reading mode (visual reference)
  paragraph.scrollIntoView({ behavior: "smooth", block: "center" });

}


/* =========================
WORD PANEL BUILDER
========================= */

// PURPOSE:
// Turn a sentence into clickable word buttons
// each word becomes an interaction trigger for graph building

function buildWordPanel(text) {

  const words = tokenize(text);

  const panel = document.getElementById("word-panel");

  panel.innerHTML = ""; // clear old buttons

  words.forEach(word => {

    const btn = document.createElement("button");
    btn.textContent = word;

    btn.addEventListener("click", () => {

      // store current selected word globally
      App.activeWord = word;

      // generate co-occurrence graph
      renderGraph(word);

    });

    panel.appendChild(btn);

  });

}


/* =========================
CO-OCCURRENCE ENGINE (CORE LOGIC)
========================= */

// PURPOSE:
// Given a word:
// find all sentences containing it,
// then count which other words appear with it

function computeCooccurrence(word) {

  const counts = {};

  // loop through all sentences in dataset
  App.graphCache.forEach(entry => {

    // skip sentences that do not contain selected word
    if (!entry.words.includes(word)) return;

    // remove target word itself (we don’t count self-cooccurrence)
    const coWords = entry.words.filter(w => w !== word);

    const uniqueCoWords = new Set(coWords);

    uniqueCoWords.forEach(w => {

      if (!counts[w]) {
        counts[w] = {
          total: 0,     // frequency count
          types: new Set() // tracks figurative type diversity
        };
      }

      // increment occurrence count
      counts[w].total += 1;

      // track whether word came from metaphor/simile/aphorism context
      counts[w].types.add(entry.type);

    });

  });

  // convert into simple numeric scores for graph ranking
  const result = {};

  Object.entries(counts).forEach(([w, data]) => {

    // boost words that appear across multiple figurative types
    const typeBonus = data.types.size * 2;

    result[w] = data.total + typeBonus;

  });

  return result;

}


/* =========================
GRAPH RENDERING (SVG)
========================= */

// PURPOSE:
// Convert co-occurrence data into a visual bar chart (SVG)

function renderGraph(word) {

  const data = computeCooccurrence(word);

  const svgNS = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(svgNS, "svg");

  // sort words by strength and keep top 10
  const entries = Object.entries(data)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);

  const barSpacing = 100;
  const baseOffset = 50;

  const width = baseOffset + entries.length * barSpacing;

  svg.setAttribute("width", width);
  svg.setAttribute("height", "300");

  entries.forEach(([w, count], i) => {

    // draw bar
    const rect = document.createElementNS(svgNS, "rect");

    rect.setAttribute("x", 50 + i * 100);
    rect.setAttribute("y", 250 - count * 20);
    rect.setAttribute("width", 20);
    rect.setAttribute("height", count * 20);

    // clicking a bar drills into deeper metaphor view
    rect.addEventListener("click", () => {
      openMetaphorView(word, w);
    });

    svg.appendChild(rect);

    // label under bar
    const label = document.createElementNS(svgNS, "text");
    label.setAttribute("x", 50 + i * 100);
    label.setAttribute("y", 270);
    label.textContent = w;

    svg.appendChild(label);

  });

  // insert SVG into DOM
  const container = document.getElementById("graph-container");
  container.innerHTML = "";
  container.appendChild(svg);

}


/* =========================
EXPANDED RESULT VIEW
========================= */

// PURPOSE:
// Show all sentences where BOTH selected words co-occur

function openMetaphorView(wordA, wordB) {

  showView("metaphor-view");

  const results = App.sentenceCache.filter(entry =>
    entry.words.includes(wordA) &&
    entry.words.includes(wordB)
  );

  const container = document.getElementById("metaphor-results");

  container.innerHTML = "";

  results.forEach(entry => {

    const div = document.createElement("div");

    // show original HTML of sentence
    div.innerHTML = entry.el.innerHTML;

    div.style.cursor = "pointer";
    div.style.marginBottom = "12px";
    div.style.padding = "8px";

    // highlight sentences containing figurative language
    if (entry.hasFigurative) {
      div.style.borderLeft = "4px solid gold";
      div.style.background = "rgba(255, 215, 0, 0.08)";
    }

    // clicking a result returns to reading view and scrolls to sentence
    div.addEventListener("click", () => {

      const el = entry.el;

      showView("reading-view");

      el.scrollIntoView({ behavior: "smooth", block: "center" });

      el.style.background = "yellow";

    });

    container.appendChild(div);

  });

}
