<?xml version="1.0" encoding="UTF-8"?>

<!-- Declares this file as an XSLT stylesheet -->
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<!-- Output will be HTML (not XML), so browser renders it as a web page -->
<xsl:output method="html"/>


<!-- ========================= -->
<!-- ROOT TEMPLATE (ENTRY POINT) -->
<!-- ========================= -->

<!-- This matches the ROOT of your XML document.
     Everything inside here builds the full HTML page. -->
<xsl:template match="/">

<html>

<head>

<title>Dorian Gray Text</title>

<link rel="stylesheet" href="css/style.css"/>

<script src="js/app.js"></script>

<style>

/* Basic page styling */
body {
    background: #f4f1ea;
    font-family: Georgia, serif;
    margin: 0;
    padding: 0;
}

/* Navigation bar styling */
nav {
    display: flex;
    gap: 15px;
    padding: 15px 25px;
    background: #222;
}

/* Navigation links */
nav a {
    color: white;
    text-decoration: none;
}

/* Main application container */
#app {
    padding: 20px;
}

/* Button container spacing */
#controls {
    margin: 20px 0;
}

/* Button styling */
button {
    margin-right: 10px;
    padding: 8px 12px;
}

/* Reading layout container */
.reading-container {
    max-width: 750px;
    margin: 0 auto;
    background: white;
    padding: 40px 50px;
    box-shadow: 0 8px 30px rgba(0,0,0,0.08);
    line-height: 1.7;
    font-size: 18px;
}

/* Paragraph spacing + indentation */
p {
    margin: 0 0 18px 0;
    text-indent: 1.5em;
}


/* ========================= */
/* FIGURATIVE LANGUAGE STYLING */
/* ========================= */

/* These target the *actual HTML tags* generated by XSLT:
   <metaphor>, <simile>, <aphorism> */

metaphor {
    background: rgba(255, 200, 0, 0.35);
    padding: 2px 4px;
    border-radius: 4px;
    cursor: pointer;
}

simile {
    background: rgba(100, 160, 255, 0.35);
    padding: 2px 4px;
    border-radius: 4px;
    cursor: pointer;
}

aphorism {
    background: rgba(180, 255, 180, 0.35);
    padding: 2px 4px;
    border-radius: 4px;
    cursor: pointer;
}

/* View system: hidden by default */
.view {
    display: none;
}

/* Only the active view is shown */
.view.active {
    display: block;
}

</style>

</head>

<body>

<nav>
    <a href="#">Home</a>
    <a href="#">Text</a>
    <a href="#">Project</a>
</nav>

<div id="app">

    <div id="controls">
        <button id="view-reading">Reading</button>
        <button id="view-metaphor">Metaphor View</button>
        <button id="view-analysis">Analysis</button>
    </div>


    <!-- ========================= -->
    <!-- READING VIEW -->
    <!-- ========================= -->

    <div id="reading-view" class="view active">

        <div class="reading-container">

            <!-- This is the MAIN transformation trigger:
                 it finds EVERY <paragraph> node in the XML
                 and applies the paragraph template to each one -->
            <xsl:apply-templates select="//paragraph"/>

        </div>

    </div>


    <!-- ANALYSIS VIEW (JS fills this dynamically) -->
    <div id="analysis-view" class="view">
        <h2>Analysis View</h2>

        <div id="analysis-sentence"></div>
        <div id="word-panel"></div>
        <div id="graph-container"></div>
    </div>


    <!-- METAPHOR VIEW (JS fills this dynamically) -->
    <div id="metaphor-view" class="view">
        <h2>Metaphor Connections</h2>
        <div id="metaphor-results"></div>
    </div>

</div>

</body>
</html>

</xsl:template>


<!-- ========================= -->
<!-- PARAGRAPH TEMPLATE -->
<!-- ========================= -->

<xsl:template match="paragraph">

<!-- Creates an HTML <p> for each XML <paragraph> -->

<p id="p-{count(preceding::paragraph) + 1}">

    <!-- 🔥 IMPORTANT LINE EXPLAINED:

         count(preceding::paragraph)
         → counts how many <paragraph> nodes come BEFORE this one in document order

         + 1
         → converts from 0-based indexing to human-readable numbering

         p-{ ... }
         → XSLT "attribute value template" syntax:
           evaluates expression inside {} and injects into string

         RESULT:
         first paragraph → p-1
         second → p-2
         etc.
    -->

    <!-- Processes all child nodes inside paragraph (text + tags) -->
    <xsl:apply-templates/>

</p>

</xsl:template>


<!-- ========================= -->
<!-- FIGURATIVE LANGUAGE TEMPLATE -->
<!-- ========================= -->

<xsl:template match="metaphor | simile | aphorism">

<!-- This template runs whenever XSLT encounters:
     <metaphor>, <simile>, or <aphorism> in XML -->

<!-- 🔥 xsl:element allows dynamic tag creation -->
<!-- name="{name()}" means:
     → take the current node name ("metaphor", "simile", etc.)
     → use it as the OUTPUT tag name -->

<xsl:element name="{name()}">

    <!-- ========================= -->
    <!-- data-type attribute -->
    <!-- ========================= -->

    <xsl:attribute name="data-type">

        <!-- name() returns the CURRENT XML element name:
             metaphor / simile / aphorism -->
        <xsl:value-of select="name()"/>

    </xsl:attribute>


    <!-- ========================= -->
    <!-- data-sentence attribute -->
    <!-- ========================= -->

    <xsl:attribute name="data-sentence">

        <!-- 🔥 THIS IS A POSITION-BASED ID SYSTEM:

             ancestor::paragraph
             → finds the paragraph this element is inside

             preceding::paragraph
             → counts how many paragraphs come BEFORE it globally

             count(...)
             → gives number of previous paragraphs

             concat('p-', ...)
             → builds string like "p-3"
        -->

        <xsl:value-of select="
            concat(
              'p-',
              count(ancestor::paragraph/preceding::paragraph) + 1
            )
        "/>

    </xsl:attribute>


    <!-- Output the inner text of the metaphor/simile/aphorism -->
    <xsl:apply-templates/>

</xsl:element>

</xsl:template>


<!-- ========================= -->
<!-- TEXT NODE TEMPLATE -->
<!-- ========================= -->

<xsl:template match="text()">

<!-- Outputs raw text exactly as-is from XML -->
<xsl:value-of select="."/>

</xsl:template>

</xsl:stylesheet>
